name: Go Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22"]
        platform:
          [
            { os: windows, arch: amd64, suffix: .exe },
            { os: linux, arch: amd64 },
            { os: darwin, arch: amd64 },
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        env:
          GOOS: ${{ matrix.platform.os }}
          GOARCH: ${{ matrix.platform.arch }}
        run: |
          mkdir -p release
          go build -v -o "release/${GOOS}_${GOARCH}/hmq_${GOOS}_${GOARCH}${{ matrix.platform.suffix }}" .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.os }}-${{ matrix.platform.arch }}
          path: release/${{ matrix.platform.os }}_${{ matrix.platform.arch }}/
  release:
    name: Create Release
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            artifacts/*
